[package]
name = "parse-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.10.0"
clap = { version = "4.0.29", features = ["derive"] }
num-traits = "0.2.15"
