name = "Petalo"
uuid = "99f2aae4-53cc-4a67-a30b-d0fe8a0d6e61"
authors = ["Jacek Generowicz <jacg@my-post-office.net>"]
version = "0.1.0"

[deps]
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
